CREATE TABLE categories (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE files (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
        name VARCHAR(30) UNIQUE NOT NULL
);
